AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  cgGatewayList:
    Default: '<GatewayIp:Secret>,...'
    Description: 'REQUIRED - CSV String of CloudGuard Security Gateway IPs (e.g. 54.1.1.10:12345D8Bgt,54.1.1.11:12345D8Bgt).'
    Type: String
  lambdaCodeS3Bucket:
    Default: '<S3-bucket-name>'
    Description: 'S3 Bucket path of lambda deployment zip file with dependencies preinstalled.'
    Type: String

Resources:
  InputTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: 'Identity Awareness Input Topic'
      TopicName: 'cpgw-ia-input'

  CpGwIdentityAwarenessFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: CpGwIdentityAwarenessFunction
      Description: 'Check Point Gateway - SNS to Identity Awareness API integration'
      CodeUri:
        Bucket: 
          Ref: lambdaCodeS3Bucket
        Key: 'ia_lambda_function.zip'
      Runtime: python3.6
      Timeout: 30 
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          cgGatewayList: ''
      Events:
        d9Findings:
          Type: SNS
          Properties:
            Topic: !Ref InputTopic 
      Policies:
        - 'AWSLambdaVPCAccessExecutionRole'

Outputs:
  InputTopicARN:
    Description: 'ARN that Dome9 sends events to'
    Value: !Ref InputTopic

